name: CI

on:
  push:
    branches: [ master, dev, td, dev-td ]

  workflow_dispatch:

jobs:
  test-difftest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get install git help2man perl python3 make autoconf g++ flex bison
          sudo apt-get install libgoogle-perftools-dev numactl
          sudo apt-get install libfl2
          sudo apt-get install libfl-dev
          sudo apt-get install zlibc zlib1g zlib1g-dev
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.018
          autoconf
          ./configure CC=clang CXX=clang++ LINK=clang++
          make -j2
          sudo make install
          sudo curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.1/0.11.1 > /usr/local/bin/mill
          chmod +x /usr/local/bin/mill
          sudo apt install libsdl2-dev

      - name: Build EMU
        run: |
          make init
          make emu -j2

      - name: CoreMark
        run: |
          ./build/emu -F ./bin/coremark.bin --diff ./bin/riscv64-nemu-interpreter-so

      - name: riscv-tests
        run: |
          bash bin/riscv-tests.sh

      - name: RT-Thread
        run: |
          ./build/emu -F ./bin/rtthread.bin --diff ./bin/riscv64-nemu-interpreter-so -I 1000000
