name: Nightly Regression
on:
  schedule:
    # run at 19:33 UTC (3:07 UTC+8)
    - cron: '07 19 * * *'

jobs:
  release:
    runs-on: nightly
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: |
          sudo apt-get install git help2man perl python3 make autoconf g++ flex bison
          sudo apt-get install libgoogle-perftools-dev numactl perl-doc
          sudo apt-get install libfl2
          sudo apt-get install libfl-dev
          sudo apt-get install zlibc zlib1g zlib1g-dev
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.018
          autoconf
          ./configure CC=clang CXX=clang++ LINK=clang++
          make -j2
          sudo make install
          sudo curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.1/0.11.1 > /usr/local/bin/mill
          chmod +x /usr/local/bin/mill
          sudo apt install libsdl2-dev

      - name: Build EMU
        run: |
          make init
          make emu -j2

      - name: CoreMark
        run: |
          ./build/emu -F ./bin/coremark.bin --diff ./bin/riscv64-nemu-interpreter-so | tee coremark.log

      - name: Release
        run: |
          make clean
          make release
          bash /home/xuyinan/piper/autobump.sh CPU.v coremark.log
